spring.application.name=eureka-server
server.port=8761
# Eureka server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# Optional: Eureka server self-preservation settings
eureka.server.enable-self-preservation=true
# Optional: Cleanup interval (milliseconds)
eureka.server.eviction-interval-timer-in-ms=60000